version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:14.16.1

jobs:
  test:
    <<: *defaults
    steps:
    - checkout
    - run: npm install
    - run: npm run lint
    - run: npm test
    - run: npm run build
workflows:
  version: 2
  test:
    jobs:
    - test
